<a href="https://colab.research.google.com/github/TharaPR/Learnings_from_CodeBasics/blob/main/ExercisePredictSalaryLinearRegWithMultipleVariables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [28]:
exp_list = [None, None, 'five', 'two', 'seven', 'three', 'ten', 'eleven']
test_score_list = [8,8,6,10,9,7,None,7]
interview_score_list = [9,6,7,10,6,10,7,8]
salary_list = [50000,45000,60000,65000,70000,62000,72000,80000]

dict = {'experience': exp_list, 'test_score': test_score_list, 'interview_score':interview_score_list, 'salary($)':salary_list}

df = pd.DataFrame(data=dict)
df

experience  test_score  interview_score  salary($)
0       None         8.0                9      50000
1       None         8.0                6      45000
2       five         6.0                7      60000
3        two        10.0               10      65000
4      seven         9.0                6      70000
5      three         7.0               10      62000
6        ten         NaN                7      72000
7     eleven         7.0                8      80000

In [29]:
df.experience = df.experience.fillna('Zero')
df

experience  test_score  interview_score  salary($)
0       Zero         8.0                9      50000
1       Zero         8.0                6      45000
2       five         6.0                7      60000
3        two        10.0               10      65000
4      seven         9.0                6      70000
5      three         7.0               10      62000
6        ten         NaN                7      72000
7     eleven         7.0                8      80000

Replace the text in Experience column with number

In [30]:
!pip install word2number
from word2number import w2n

In [31]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score  interview_score  salary($)
0           0         8.0                9      50000
1           0         8.0                6      45000
2           5         6.0                7      60000
3           2        10.0               10      65000
4           7         9.0                6      70000
5           3         7.0               10      62000
6          10         NaN                7      72000
7          11         7.0                8      80000

Fill the missing test scores with the Median of that feature

In [32]:
import math
df.test_score = df.test_score.fillna(math.floor(df.test_score.median()))
print(df)
df.columns

   experience  test_score  interview_score  salary($)
0           0         8.0                9      50000
1           0         8.0                6      45000
2           5         6.0                7      60000
3           2        10.0               10      65000
4           7         9.0                6      70000
5           3         7.0               10      62000
6          10         8.0                7      72000
7          11         7.0                8      80000


Index(['experience', 'test_score', 'interview_score', 'salary($)'], dtype='object')

Create a regression object

In [33]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience', 'test_score', 'interview_score' ]], df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [34]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [35]:
reg.intercept_

17737.263464337702

In [36]:
reg.predict([[2, 9, 6]])

array([53205.96797671])

In [37]:
-4654.29403202*2 + -93263.4643377*9 + -19017.46724891*6 + 1036820.2328966521

74035.66229985212

In [38]:
reg.predict([[12, 10, 10]])

array([92002.18340611])